<a href="https://colab.research.google.com/github/Akarsher/MCA-S3-programs/blob/main/ML/Array_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print ("hello world")

hello world


In [15]:
ones = np.ones((2,3,3))
print(ones)

print(ones.shape)
print(ones.ndim)
print(ones.dtype)
print(ones.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(2, 3, 3)
3
float64
18


In [16]:
array = np.linspace(1,25,4)
array

array([ 1.,  9., 17., 25.])

In [21]:
die = np.random.randint(1,7)
print(die)

rand_2d_array= np.random.randint(50,100, size=(4,3))
rand_2d_array

6


array([[98, 52, 69],
       [68, 74, 90],
       [76, 76, 62],
       [61, 53, 76]])